rootProject.name = "identra"

include(
    "libs:common",
    "libs:canonical-model",
    "libs:adapter-spi",
    "libs:security",
    "libs:ai-spi",
    "adapters:okta",
    "adapters:sailpoint-isc",
    "adapters:identity-core",
    "adapters:entra",
    "adapters:saviynt",
    "services:api-gateway",
    "services:tenant-service",
    "services:identity-service",
    "services:provisioning-service",
    "services:adapter-runtime",
    "services:audit-service",
    "services:approval-service",
    "services:ai-gateway",
    "services:governance-service",
    "services:connector-factory",
    "services:identity-core-service",
    "services:migration-service",
    "services:marketplace-service",
    "apps:admin-bff",
)
