package com.identra.ai.gateway.provider;

import com.identra.ai.LlmProvider;
import com.identra.ai.LlmRequest;
import com.identra.ai.LlmResponse;
import org.springframework.stereotype.Component;

import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Local deterministic provider used when cloud LLMs are not configured.
 * Never sends secrets; strips obvious credential patterns from prompts.
 */
@Component
public class LocalTemplateLlmProvider implements LlmProvider {

    private static final Set<String> MODELS = Set.of("local-template", "llama-local", "mistral-local");

    @Override
    public String id() {
        return "local";
    }

    @Override
    public boolean supports(String model) {
        return model == null || MODELS.contains(model.toLowerCase(Locale.ROOT));
    }

    @Override
    public LlmResponse complete(LlmRequest request) {
        String prompt = request.messages() == null || request.messages().isEmpty()
                ? ""
                : request.messages().getLast().content();
        String sanitized = sanitize(prompt);
        String content = """
                {
                  "connectorClass": "GeneratedRestConnector",
                  "authType": "OAUTH2",
                  "operations": ["CREATE", "UPDATE", "DISABLE", "DELETE", "RESET_PASSWORD"],
                  "schema": {"userName": "string", "email": "string", "active": "boolean"},
                  "notes": "Generated by Identra local LLM provider",
                  "promptDigest": "%s"
                }
                """.formatted(Integer.toHexString(sanitized.hashCode()));
        return new LlmResponse(
                id(),
                request.model() == null ? "local-template" : request.model(),
                content,
                sanitized.length() / 4,
                content.length() / 4,
                Map.of("mode", "dry-run", "piiRedacted", true)
        );
    }

    static String sanitize(String input) {
        if (input == null) {
            return "";
        }
        return input
                .replaceAll("(?i)(api[_-]?key|password|secret|token)\\s*[:=]\\s*\\S+", "$1=[REDACTED]")
                .replaceAll("(?i)Bearer\\s+\\S+", "Bearer [REDACTED]");
    }
}
